### ISSUE TITLE
Permanent Open

### ISSUE THREAD

**Issue by LordKhaox** [Jarada/WuufusWaygates#1]
Maybe u could add an option to keep the portal open until u change it with the key?

**Comment by Jarada** [comment]
Hi there,

Thank you for this feature request! I would like your thoughts on the below and whether or not this is something you'd still want after understanding the reasoning that gates are currently set to time out.

Given the nature of the plugin to create Waygates out of any material, a lot of the players that I have seen create gates have made them inside their base. I have seen many gates that are completely integrated into the base, often hidden with inset emerald blocks so you don't know it's there until you are right on top, or acting as door frames between two rooms. These kind of gates would not be possible on always-on portals, as they would stand out as gates immediately and would not allow walking through them as a door frame.

Expanding on this, many of the Waygates that are presented are set to Private, so that only those who own these Waygates can activate them. Some Waygates that aren't private are set to private networks, hidden from other players. By having the gates close after a set time period, it means these private gates cannot be traversed at all if you are not the owner or an admin, but that players can easily choose to take friends through even if the friend cannot activate the gate themselves. If left open, these gates can be traversed by anyone and it would undermine private gates and private networks.

Finally, the noise of the nether portal blocks themselves while you are home doing extensive crafting projects, or just meandering around the house, may be off putting to a lot of players. It would mean they'd move gates away from their homes into special gate rooms instead.

As stated before, I'd be very interested in hearing your thoughts as to whether this is something that you agree with and the use cases you see for always open gates. It is very easy to add such a feature, so if this is something you'd still see having a use for I will endeavour to implement it as a configuration switch.

**Comment by Jarada** [comment]
Closing this issue now. Doesn't mean this won't be added in the future but it isn't an immediate priority.
