### ISSUE TITLE
Permission Issue - All networks except a single one?

### ISSUE THREAD

**Issue by drakmirv** [Jarada/WuufusWaygates#8]
How to specify that users can assign to any global network EXCEPT a particular one?

I tried:

wg.network.global   true
wg.network.specific false

but the permission check seems to stop at the 1st one and not take the "false" permission into account.

**Comment by Jarada** [comment]
Currently the plugin does not allow for this kind of permissioning. If `wg.network.global` is set, then the specific permissions are ignored. So in order to achieve what you are wanting to achieve, you'd need to add permissions for each network apart from the one you are not wanting to access.

I will have a think as to the best way to implement an exclusion of a network from the global permission.

**Comment by drakmirv** [comment]
Makes sense.  My goal was to allow global networks to be created by the
players but keep some global networks "admin only".

Since I wasn't planning on using fixed networks, I guess I can move my
admin networks to be of fixed type and let that happen.

I think I may be able to solve it this way with Luck Perms.  I'll try later
on and report back:

wg.network.* true
wg.network.x false
remove wg.network.global true

**Comment by Jarada** [comment]
The way I originally saw admin networks working is to setup an Invite Network for admins, since such a restricted network is not really "global" in its nature. As owner of the network you can then invite specific users (your admins) to that network, and only they can then add gates to the network.

Let me know if your network permissioning works also if you decide to go that route :)

**Comment by drakmirv** [comment]
Can users use the gates if we use an invite network?

I'm good with that concept - the gate in this case is my "tutorials"
network.  :)

**Comment by Jarada** [comment]
Yes, all users will be able to use the gates unless they are set to private, and travel to the gates unless they are set to hidden, and then it would just be the owner of the gate that can travel from/to the gate respectively (or `wg.admin` or `wg.bypass` users). 

The network type just influences who can join gates to a network and how the network itself operates.

**Comment by drakmirv** [comment]
Thanks for the clarity.  Invite networks seem like the right solution then.

**Comment by Jarada** [comment]
Awesome. I'll close this issue :)
